import pako from "pako";

const data = [
  {
    Value: "--",
    Display: true,
    Category: "Brand",
    Matching: "Brand",
    Mandatory: false,
    Type: "S",
    Preference: false,
    Important: false,
    HigherNumber: true,
  },
  {
    Value: "--",
    Display: true,
    Category: "Model",
    Matching: "Model",
    Mandatory: false,
    Type: "S",
    Preference: false,
    Important: false,
    HigherNumber: true,
  },
  {
    Value: "--",
    Display: true,
    Category: "Year",
    Matching: "Year",
    Mandatory: false,
    Type: "S",
    Preference: false,
    Important: false,
    HigherNumber: true,
  },
  {
    Value: "--",
    Display: true,
    Category: "Trim",
    Matching: "Trim",
    Mandatory: false,
    Type: "S",
    Preference: false,
    Important: false,
    HigherNumber: true,
  },
  {
    Value: "Add at least 2 items to view the pros",
    Display: true,
    Category: "Pros",
    Matching: "Pros",
    Mandatory: false,
    Type: "S",
    Preference: false,
    Important: false,
    HigherNumber: false,
  },
  {
    Value: "Body Type: --",
    Display: true,
    Category: "Body",
    Matching: "Body Type",
    Mandatory: false,
    Type: "S",
    Preference: true,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "Powertrain: --",
    Display: true,
    Category: "Motor",
    Matching: "Powertrain",
    Mandatory: false,
    Type: "S",
    Preference: true,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "Drivetrain: --",
    Display: true,
    Category: "Motor",
    Matching: "Drivetrain",
    Mandatory: false,
    Type: "S",
    Preference: true,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "Seats: --",
    Display: true,
    Category: "Design",
    Matching: "Seats",
    Mandatory: true,
    Type: "N",
    Preference: true,
    Important: true,
    HigherNumber: true,
  },
  {
    Value: "Doors: --",
    Display: true,
    Category: "Design",
    Matching: "Doors",
    Mandatory: true,
    Type: "N",
    Preference: true,
    Important: true,
    HigherNumber: true,
  },
  {
    Value: "Fuel Consumption (City): --",
    Display: false,
    Category: "Fuel/Battery",
    Matching: "Fuel Consumption (City)",
    Mandatory: true,
    Type: "N",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "Fuel Consumption (Highway): --",
    Display: false,
    Category: "Fuel/Battery",
    Matching: "Fuel Consumption (Highway)",
    Mandatory: true,
    Type: "N",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "Fuel Consumption (Combined): --",
    Display: false,
    Category: "Fuel/Battery",
    Matching: "Fuel Consumption (Combined)",
    Mandatory: false,
    Type: "N",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "Fuel Type: --",
    Display: true,
    Category: "Fuel/Battery",
    Matching: "Fuel Type",
    Mandatory: false,
    Type: "S",
    Preference: true,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "Power: --",
    Display: true,
    Category: "Motor",
    Matching: "Power",
    Mandatory: true,
    Type: "N",
    Preference: false,
    Important: true,
    HigherNumber: true,
  },
  {
    Value: "Torque: --",
    Display: true,
    Category: "Motor",
    Matching: "Torque",
    Mandatory: true,
    Type: "N",
    Preference: false,
    Important: true,
    HigherNumber: true,
  },
  {
    Value: "Valvetrain: --",
    Display: false,
    Category: "Motor",
    Matching: "Valvetrain",
    Mandatory: false,
    Type: "S",
    Preference: true,
    Important: true,
    HigherNumber: true,
  },
  {
    Value: "Valves: --",
    Display: false,
    Category: "Motor",
    Matching: "Valves",
    Mandatory: true,
    Type: "N",
    Preference: false,
    Important: true,
    HigherNumber: true,
  },
  {
    Value: "Cylinders: --",
    Display: false,
    Category: "Motor",
    Matching: "Cylinders",
    Mandatory: true,
    Type: "S",
    Preference: false,
    Important: true,
    HigherNumber: true,
  },
  {
    Value: "Engine aspiration: --",
    Display: false,
    Category: "Motor",
    Matching: "Engine aspiration",
    Mandatory: false,
    Type: "S",
    Preference: true,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "Curb Weight: --",
    Display: true,
    Category: "Body",
    Matching: "Curb Weight",
    Mandatory: true,
    Type: "N",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "Length: --",
    Display: true,
    Category: "Body",
    Matching: "Length",
    Mandatory: false,
    Type: "N",
    Preference: true,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "Width: --",
    Display: true,
    Category: "Body",
    Matching: "Width",
    Mandatory: false,
    Type: "N",
    Preference: true,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "Height: --",
    Display: true,
    Category: "Body",
    Matching: "Height",
    Mandatory: false,
    Type: "N",
    Preference: true,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "Wheelbase: --",
    Display: true,
    Category: "Body",
    Matching: "Wheelbase",
    Mandatory: false,
    Type: "N",
    Preference: true,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "Tire Size: --",
    Display: true,
    Category: "Design",
    Matching: "Tire Size",
    Mandatory: false,
    Type: "N",
    Preference: false,
    Important: false,
    HigherNumber: true,
  },
  {
    Value: "Rim Size: --",
    Display: true,
    Category: "Design",
    Matching: "Rim size",
    Mandatory: false,
    Type: "N",
    Preference: false,
    Important: false,
    HigherNumber: true,
  },
  {
    Value: "Gears: --",
    Display: true,
    Category: "Motor",
    Matching: "Gears",
    Mandatory: true,
    Type: "N",
    Preference: false,
    Important: true,
    HigherNumber: true,
  },
  {
    Value: "Transmission: --",
    Display: true,
    Category: "Motor",
    Matching: "Transmission",
    Mandatory: false,
    Type: "S",
    Preference: true,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "Battery Capacity: --",
    Display: false,
    Category: "Fuel/Battery",
    Matching: "Battery Capacity",
    Mandatory: true,
    Type: "N",
    Preference: false,
    Important: true,
    HigherNumber: true,
  },
  {
    Value: "Electric Range: --",
    Display: false,
    Category: "Fuel/Battery",
    Matching: "Electric Range",
    Mandatory: true,
    Type: "S",
    Preference: false,
    Important: true,
    HigherNumber: true,
  },
];

const stringifiedData = JSON.stringify(data);

// Convert the url to a Uint8Array
const inputUint8Array = new TextEncoder().encode(stringifiedData);

// Compress the url
const compressed = pako.deflate(inputUint8Array);

// Convert the compressed url back to a string (base64 in this case)
const compressedBase64 = btoa(
  String.fromCharCode(...new Uint8Array(compressed))
);

console.log(compressedBase64);
