const pako = require("pako");

// Original data
const data =
  "This is a long string that we want to compress. This is a long string that we want to compress. This is a long string that we want to compress. This is a long string that we want to compress. This is a long string that we want to compress. This is a long string that we want to compress. This is a long string that we want to compress.";

const consoleDefaultArray = [
  {
    Value: "--",
    Display: true,
    Category: "Brand",
    Matching: "Brand",
    Mandatory: false,
    Type: "S",
    Preference: false,
    Important: false,
    HigherNumber: false,
  },
  {
    Value: "--",
    Display: true,
    Category: "Name",
    Matching: "Name",
    Mandatory: false,
    Type: "S",
    Preference: false,
    Important: false,
    HigherNumber: false,
  },
  {
    Value: "Add at least 2 items to view the pros",
    Display: true,
    Category: "Pros",
    Matching: "Pros",
    Mandatory: false,
    Type: "S",
    Preference: false,
    Important: false,
    HigherNumber: false,
  },
  {
    Value: "Clock Speed: --",
    Display: true,
    Category: "CPU",
    Matching: "cpu speed",
    Mandatory: true,
    Type: "S",
    Preference: false,
    Important: true,
    HigherNumber: true,
  },
  {
    Value: "Floating-Point Performance: --",
    Display: true,
    Category: "CPU",
    Matching: "floating-point performance",
    Mandatory: true,
    Type: "N",
    Preference: false,
    Important: true,
    HigherNumber: true,
  },
  {
    Value: "Capacity: --",
    Display: true,
    Category: "RAM",
    Matching: "ram",
    Mandatory: true,
    Type: "S",
    Preference: false,
    Important: true,
    HigherNumber: true,
  },
  {
    Value: "Clock Speed: --",
    Display: true,
    Category: "GPU",
    Matching: "gpu clock speed",
    Mandatory: true,
    Type: "N",
    Preference: false,
    Important: true,
    HigherNumber: true,
  },
  {
    Value: "Ray Tracing",
    Display: false,
    Category: "GPU",
    Matching: "supports ray tracing",
    Mandatory: true,
    Type: "B",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "I/O Throughput: --",
    Display: true,
    Category: "Storage",
    Matching: "i/o throughput",
    Mandatory: true,
    Type: "N",
    Preference: false,
    Important: true,
    HigherNumber: true,
  },
  {
    Value: "GDDR Version: --",
    Display: true,
    Category: "GPU",
    Matching: "gddr version",
    Mandatory: true,
    Type: "S",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "NVME SSD",
    Display: false,
    Category: "Storage",
    Matching: "is an nvme ssd",
    Mandatory: true,
    Type: "B",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "Bandwidth: --",
    Display: true,
    Category: "RAM",
    Matching: "memory bandwidth",
    Mandatory: true,
    Type: "N",
    Preference: false,
    Important: true,
    HigherNumber: true,
  },
  {
    Value: "Accepts External Drive",
    Display: false,
    Category: "Storage",
    Matching: "can connect to an external drive",
    Mandatory: true,
    Type: "B",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "Shading Units: --",
    Display: true,
    Category: "GPU",
    Matching: "shading units",
    Mandatory: true,
    Type: "N",
    Preference: false,
    Important: true,
    HigherNumber: true,
  },
  {
    Value: "Compute Units: --",
    Display: true,
    Category: "GPU",
    Matching: "number of compute units",
    Mandatory: true,
    Type: "N",
    Preference: false,
    Important: true,
    HigherNumber: true,
  },
  {
    Value: "ROPs: --",
    Display: true,
    Category: "GPU",
    Matching: "render output units (rops)",
    Mandatory: true,
    Type: "N",
    Preference: false,
    Important: true,
    HigherNumber: true,
  },
  {
    Value: "Uses Multithreading",
    Display: false,
    Category: "CPU",
    Matching: "uses multithreading",
    Mandatory: true,
    Type: "B",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "Refresh Rate: --",
    Display: true,
    Category: "Display",
    Matching: "refresh rate",
    Mandatory: true,
    Type: "S",
    Preference: false,
    Important: true,
    HigherNumber: true,
  },
  {
    Value: "DDR Version: --",
    Display: true,
    Category: "RAM",
    Matching: "ddr memory version",
    Mandatory: true,
    Type: "N",
    Preference: false,
    Important: true,
    HigherNumber: true,
  },
  {
    Value: "Clock Speed: --",
    Display: true,
    Category: "RAM",
    Matching: "ram speed",
    Mandatory: true,
    Type: "N",
    Preference: false,
    Important: true,
    HigherNumber: true,
  },
  {
    Value: "--",
    Display: true,
    Category: "Portability",
    Matching: "type",
    Mandatory: true,
    Type: "S",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "Max Resolution: --",
    Display: true,
    Category: "Display",
    Matching: "output resolution",
    Mandatory: true,
    Type: "S",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "Replaceable Hard Drive",
    Display: false,
    Category: "Storage",
    Matching: "hard drive is replaceable",
    Mandatory: true,
    Type: "B",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "Internal Power Supply",
    Display: false,
    Category: "Power",
    Matching: "has an internal power supply",
    Mandatory: false,
    Type: "B",
    Preference: false,
    Important: false,
    HigherNumber: false,
  },
  {
    Value: "Internal Storage",
    Display: false,
    Category: "Storage",
    Matching: "internal storage",
    Mandatory: true,
    Type: "S",
    Preference: false,
    Important: true,
    HigherNumber: true,
  },
  {
    Value: "Region Free",
    Display: false,
    Category: "Games",
    Matching: "is region free",
    Mandatory: true,
    Type: "B",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "--",
    Display: true,
    Category: "Height",
    Matching: "thickness",
    Mandatory: true,
    Type: "N",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "--",
    Display: true,
    Category: "Width",
    Matching: "width",
    Mandatory: true,
    Type: "N",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "--",
    Display: true,
    Category: "Length",
    Matching: "height",
    Mandatory: true,
    Type: "N",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "--",
    Display: true,
    Category: "Size",
    Matching: "volume",
    Mandatory: true,
    Type: "N",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "Optical Disc Drive",
    Display: false,
    Category: "Ports",
    Matching: "has an optical disc drive",
    Mandatory: true,
    Type: "B",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "--",
    Display: true,
    Category: "Weight",
    Matching: "weight",
    Mandatory: true,
    Type: "S",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "Maximum Operating Temperature: --",
    Display: true,
    Category: "Operating Temperature",
    Matching: "maximum operating temperature",
    Mandatory: true,
    Type: "N",
    Preference: false,
    Important: true,
    HigherNumber: true,
  },
  {
    Value: "Minimum Operating Temperature: --",
    Display: true,
    Category: "Operating Temperature",
    Matching: "lowest potential operating temperature",
    Mandatory: true,
    Type: "N",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "Battery Capacity: --",
    Display: true,
    Category: "Power",
    Matching: "battery power",
    Mandatory: false,
    Type: "N",
    Preference: false,
    Important: true,
    HigherNumber: true,
  },
  {
    Value: "3.5mm Audio",
    Display: false,
    Category: "Ports",
    Matching: "has a socket for a 3.5 mm audio jack",
    Mandatory: true,
    Type: "B",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "Wi-Fi",
    Display: false,
    Category: "Connectivity",
    Matching: "supports wi-fi",
    Mandatory: true,
    Type: "B",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "Wi-Fi Version: --",
    Display: true,
    Category: "Connectivity",
    Matching: "wi-fi version",
    Mandatory: true,
    Type: "S",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "DLNA-Certified",
    Display: false,
    Category: "Connectivity",
    Matching: "is dlna-certified",
    Mandatory: true,
    Type: "B",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "USB Ports: --",
    Display: true,
    Category: "Ports",
    Matching: "usb ports",
    Mandatory: true,
    Type: "N",
    Preference: false,
    Important: true,
    HigherNumber: true,
  },
  {
    Value: "HDMI",
    Display: false,
    Category: "Ports",
    Matching: "has an hdmi output",
    Mandatory: true,
    Type: "B",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "HDMI Version: --",
    Display: true,
    Category: "Ports",
    Matching: "hdmi version",
    Mandatory: true,
    Type: "S",
    Preference: false,
    Important: true,
    HigherNumber: true,
  },
  {
    Value: "External Memory Slot",
    Display: false,
    Category: "Storage",
    Matching: "has an external memory slot",
    Mandatory: true,
    Type: "B",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "Remote Play",
    Display: false,
    Category: "Connectivity",
    Matching: "supports connectivity between home and portable devices",
    Mandatory: true,
    Type: "B",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "USB Version: --",
    Display: true,
    Category: "Ports",
    Matching: "usb version",
    Mandatory: true,
    Type: "N",
    Preference: false,
    Important: true,
    HigherNumber: true,
  },
  {
    Value: "USB Type-C",
    Display: false,
    Category: "Ports",
    Matching: "has usb type-c",
    Mandatory: true,
    Type: "B",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "Cellular Data",
    Display: false,
    Category: "Connectivity",
    Matching: "has a cellular module",
    Mandatory: false,
    Type: "B",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "NFC",
    Display: false,
    Category: "Connectivity",
    Matching: "has nfc",
    Mandatory: false,
    Type: "B",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "Ethernet Ports: --",
    Display: true,
    Category: "Connectivity",
    Matching: "rj45 ports",
    Mandatory: true,
    Type: "N",
    Preference: false,
    Important: true,
    HigherNumber: true,
  },
  {
    Value: "Games (as of last database update): --",
    Display: true,
    Category: "Games",
    Matching: "number of games",
    Mandatory: false,
    Type: "N",
    Preference: false,
    Important: true,
    HigherNumber: true,
  },
  {
    Value: "Exclusive Games (as of last database update): --",
    Display: true,
    Category: "Games",
    Matching: "number of exclusive games",
    Mandatory: false,
    Type: "N",
    Preference: false,
    Important: true,
    HigherNumber: true,
  },
  {
    Value: "Voice Commands",
    Display: false,
    Category: "Audio",
    Matching: "has voice commands",
    Mandatory: false,
    Type: "B",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "Backwards Compatible",
    Display: false,
    Category: "Games",
    Matching: "backwards compatibility",
    Mandatory: true,
    Type: "B",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "Play As You Download",
    Display: false,
    Category: "Games",
    Matching: "can play games while they download",
    Mandatory: true,
    Type: "B",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "Quick Resume",
    Display: false,
    Category: "Games",
    Matching: "supports quick resume",
    Mandatory: true,
    Type: "B",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "Discord",
    Display: false,
    Category: "Audio",
    Matching: "supports discord voice chat",
    Mandatory: true,
    Type: "B",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "3D Audio",
    Display: false,
    Category: "Audio",
    Matching: "supports 3d audio",
    Mandatory: true,
    Type: "B",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "Dolby Vision",
    Display: false,
    Category: "Display",
    Matching: "supports dolby vision",
    Mandatory: false,
    Type: "B",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "VR",
    Display: false,
    Category: "Display",
    Matching: "supports vr",
    Mandatory: true,
    Type: "B",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "4k Blu-ray Drive",
    Display: false,
    Category: "Ports",
    Matching: "has a 4k blu-ray drive",
    Mandatory: true,
    Type: "B",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "Sound Output Channel: --",
    Display: true,
    Category: "Audio",
    Matching: "number of channels of sound output",
    Mandatory: true,
    Type: "N",
    Preference: false,
    Important: true,
    HigherNumber: true,
  },
  {
    Value: "Optical Tracking",
    Display: false,
    Category: "Controllers",
    Matching: "has optical tracking",
    Mandatory: true,
    Type: "B",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "Blu-ray",
    Display: false,
    Category: "Display",
    Matching: "can play blu-ray discs",
    Mandatory: true,
    Type: "B",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "High Scores and Achievements",
    Display: false,
    Category: "Games",
    Matching: "access high scores and achievements",
    Mandatory: false,
    Type: "B",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "3D",
    Display: false,
    Category: "Display",
    Matching: "supports 3d",
    Mandatory: true,
    Type: "B",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "Flash Storage",
    Display: false,
    Category: "Storage",
    Matching: "uses flash storage",
    Mandatory: true,
    Type: "B",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "Child Lock",
    Display: false,
    Category: "Games",
    Matching: "has a child lock",
    Mandatory: false,
    Type: "B",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "Maximum Controllers: --",
    Display: true,
    Category: "Controllers",
    Matching: "number of controllers",
    Mandatory: true,
    Type: "N",
    Preference: false,
    Important: true,
    HigherNumber: true,
  },
  {
    Value: "Adaptive Triggers",
    Display: false,
    Category: "Controllers",
    Matching: "has adaptive triggers",
    Mandatory: true,
    Type: "B",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "Motion-Sensing Compatible",
    Display: false,
    Category: "Controllers",
    Matching: "compatible with a motion-sensing controller(s)",
    Mandatory: true,
    Type: "B",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "Supports Wireless Controllers",
    Display: false,
    Category: "Controllers",
    Matching: "has a wireless controller",
    Mandatory: true,
    Type: "B",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "Analog Sticks: --",
    Display: true,
    Category: "Controllers",
    Matching: "number of analog sticks",
    Mandatory: true,
    Type: "N",
    Preference: false,
    Important: true,
    HigherNumber: true,
  },
  {
    Value: "Integrated Touchpad",
    Display: false,
    Category: "Controllers",
    Matching: "has an integrated touchpad",
    Mandatory: true,
    Type: "B",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "Dual Force Feedback",
    Display: true,
    Category: "Audio",
    Matching: "has dual force feedback",
    Mandatory: true,
    Type: "B",
    Preference: false,
    Important: true,
    HigherNumber: false,
  },
  {
    Value: "Controller Weight: --",
    Display: true,
    Category: "Controllers",
    Matching: "controller weight",
    Mandatory: true,
    Type: "N",
    Preference: false,
    Important: true,
    HigherNumber: true,
  },
  {
    Value: "Buttons: --",
    Display: true,
    Category: "Controllers",
    Matching: "number of buttons",
    Mandatory: true,
    Type: "N",
    Preference: false,
    Important: true,
    HigherNumber: true,
  },
  {
    Value: "Maximum External Memory",
    Display: false,
    Category: "Storage",
    Matching: "maximum amount of external memory supported",
    Mandatory: true,
    Type: "N",
    Preference: false,
    Important: true,
    HigherNumber: true,
  },
];
// Compress the data
const compressedData = pako.gzip(JSON.stringify(consoleDefaultArray));

// Convert the compressed data to a readable format (e.g., base64)
const compressedDataBase64 = Buffer.from(compressedData).toString("base64");
console.log(compressedDataBase64 + "\n");

// Decompress the data
const decompressedData = pako.ungzip(
  Buffer.from(compressedDataBase64, "base64"),
  { to: "string" }
);

console.log(decompressedData);
